apiVersion: v1
kind: Pod
metadata:
  name: test-hostdev-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: example-hostdevice-network
spec:
  containers:
    - name: test-hostdev-pod
      image: centos/tools
      imagePullPolicy: IfNotPresent
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 300; done;" ]
      resources:
        requests:
          nvidia.com/mlnx_hostdev: '1'
        limits:
          nvidia.com/mlnx_hostdev: '1'
