
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - mellanox.com
  resources:
  - hostdevicenetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mellanox.com
  resources:
  - hostdevicenetworks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mellanox.com
  resources:
  - macvlannetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mellanox.com
  resources:
  - macvlannetworks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mellanox.com
  resources:
  - nicclusterpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mellanox.com
  resources:
  - nicclusterpolicies/status
  verbs:
  - get
  - patch
  - update
