on:
  issues:
    types:
      - opened

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_NVIDIA_CI_CD }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "ISSUE_TITLE"
          
        

  update_network_operator_values:
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: "v0.0.1"
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN_NVIDIA_CI_CD }}
          repository: ${{ github.repository_owner }}/sriov-network-operator
      - name: Create PR to update image tags in network-operator values
        run: |
          git config user.name  nvidia-ci-cd
          git config user.email svc-cloud-orch-gh@nvidia.com

          git checkout -b release-4.6
          git tag $DOCKER_TAG 
          git push origin --tags
